
services:
  qwik-app:
    image: node
    container_name: qwik-app
    working_dir: /app
    volumes:
      - .:/app  # Monta el código local en el contenedor
    ports:
      - "5173:5173"  # Expone Qwik
    networks:
      - qwik-network  # Red personalizada para acceso por IP
    command: ["sh", "-c", "npm install && npm run dev -- --host"]

networks:
  qwik-network: 
    driver: bridge
